version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  verbosity: minimal
after_build:
- ps: nuget pack src\ConcurrentLinkedList -OutputDirectory .\Artifacts -Version %appveyor_build_version%
artifacts:
- path: src\ConcurrentLinkedList\Artifacts\*
deploy:
  provider: NuGet
  api_key:
    secure: IXPOCrCUrljhGbmUKteGUbtG22rLYuFTy8XUrxYf6rFuG942zE+VmMg7fFD85YoD
  skip_symbols: true
  artifact: /.*\.nupkg/
