# Master configuration with deploy
-  
branches:
  only:
    - master    
version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- ps: nuget restore
build:
  verbosity: minimal
after_build:
- ps: nuget pack src\ConcurrentLinkedList -OutputDirectory .\Artifacts -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
- path: Artifacts\*
deploy:
  provider: NuGet
  api_key:
    secure: IXPOCrCUrljhGbmUKteGUbtG22rLYuFTy8XUrxYf6rFuG942zE+VmMg7fFD85YoD
  skip_symbols: true
  artifact: /.*\.nupkg/
 
# Fallback for other branches - no deploy and debug configuration 
-
version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
before_build:
- ps: nuget restore
build:
  verbosity: minimal
